apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb1
  name: mongodb1
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: peerlink-rest
# TODO make this service serve the elastic search and mongo db at the same time using ports attributes