apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-client
  name: mongo-client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-client
    spec:
      containers:
      - env:
        - name: MONGOCLIENT_DEFAULT_CONNECTION_URL
          value: mongodb://mongo:27017
        image: mongoclient/mongoclient
        name: mongo-client
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
