apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb1
    role: database
    tier: backend
  name: mongodb1
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb1
    role: database
    tier: backend
