apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb1
  name: mongodb1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb1
    spec:
      containers:
      - image: mongo:4.0.3
        name: mogodb-container
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
