apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: peerlink
spec:
  replicas: 1
  template:
    spec:
      containers:
      - command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -Dspring.profiles.active=prod
        - -jar
        - /app.jar
        image: peerlink-rest
        name: peerlink-rest-app
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
