kind: Service
apiVersion: v1
metadata:
 name: elasticsearch
 labels:
   app: elasticsearch
spec:
 selector:
   app: elasticsearch
 clusterIP: None
 ports:
   - port: 9200
     name: rest
   - port: 9300
     name: inter-node

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster.name: my-elastic-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch-cluster
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esnode
spec: #  spec 1
  serviceName: elasticsearch
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elasticsearch  # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: elasticsearch # has to match .spec.selector.matchLabels
    spec:  # spec 2
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
          securityContext:
            privileged: true
            runAsUser: 1000
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: es-config
                  key: ES_JAVA_OPTS
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

#kind: Service
#apiVersion: v1
#metadata:
#  name: elasticsearch
#  labels:
#    app: elasticsearch
#spec:
#  selector:
#    app: elasticsearch
#  clusterIP: None
#  ports:
#    - port: 9200
#      name: rest
#    - port: 9300
#      name: inter-node
#
#---
#
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: es-cluster
#spec:
#  serviceName: elasticsearch
#  replicas: 3
#  selector:
#    matchLabels:
#      app: elasticsearch
#  template:
#    metadata:
#      labels:
#        app: elasticsearch
#    spec:
#      containers:
#        - name: elasticsearch
#          image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3
#          resources:
#            limits:
#              cpu: 1000m
#            requests:
#              cpu: 100m
#          env:
#            - name: ES_JAVA_OPTS
#              valueFrom:
#                configMapKeyRef:
#                  name: es-config
#                  key: ES_JAVA_OPTS
#          readinessProbe:
#            httpGet:
#              scheme: HTTP
#              path: /_cluster/health?local=true
#              port: 9200
#            initialDelaySeconds: 5
#          ports:
#            - containerPort: 9200
#              name: es-http
#            - containerPort: 9300
#              name: es-transport
#          volumeMounts:
#            - name: es-data
#              mountPath: /usr/share/elasticsearch/data
#            - name: elasticsearch-config
#              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
#              subPath: elasticsearch.yml
#      initContainers:
#        - name: fix-permissions
#          image: busybox
#          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
#          securityContext:
#            privileged: true
#          volumeMounts:
#            - name: data
#              mountPath: /usr/share/elasticsearch/data
#        - name: increase-vm-max-map
#          image: busybox
#          command: ["sysctl", "-w", "vm.max_map_count=262144"]
#          securityContext:
#            privileged: true
#        - name: increase-fd-ulimit
#          image: busybox
#          command: ["sh", "-c", "ulimit -n 65536"]
#          securityContext:
#            privileged: true
#  volumeClaimTemplates:
#    - metadata:
#        name: data
#        labels:
#          app: elasticsearch
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: px-ha-sc
#        resources:
#          requests:
#            storage: 10Gi
